# 定义构建变量
variables:
    # 飞书机器人的WebHook地址
    feishuWebHook: "https://open.feishu.cn/open-apis/bot/v2/hook/e4d9e8e5-6c97-4eb7-aae9-158590634c05"
    # 需要@人的飞书UID
    atFeishuUid: ""
    # 项目地址
    gitProjectPath: "/Users/yangguo/HuafangProject/slogan"
    # 需要打包的git分支
    gitBranch: "先不用打包功能"

# 定义构建前期阶段
before_script:
    - cd $gitProjectPath
    - ls
    - git fetch
    - git checkout $CI_COMMIT_BRANCH
    - git pull
    - chmod +x ./gradlew
    # 输出全局变量
#    - export
    - |
        if [ $GITLAB_USER_NAME == "郭xx" ]
        then
            echo "郭杨，您好！"
            atFeishuUid="xxxxx"
        elif [ $GITLAB_USER_NAME == "周xx" ]
        then
            echo "周咏龙，您好！"
            atFeishuUid="xxxx"
        fi

# 定义构建阶段
stages:
    - build-merge
    - notify-merge-success
    - notify-merge-fail
    - build-push
    - notify-push

include:
    - /yml/merge_request_pipelines.yml
    - /yml/push_pipelines.yml